### ISSUE TITLE
display failure

### ISSUE THREAD

**Issue by JeffBezanson** [timholy/ImageView.jl#13]
This happens on linux (ubuntu 12.04) with tcl/tk 8.5:

```
julia> imgc, imsl = ImageView.display(img)
ERROR: getgc: Canvas is not drawable
 in wait_initialized at /home/jeff/.julia/Tk/src/tkwidget.jl:416
 in getgc at /home/jeff/.julia/Tk/src/tkwidget.jl:422
 in set_coords at /home/jeff/.julia/ImageView/src/display.jl:528
 in resize at /home/jeff/.julia/ImageView/src/display.jl:438
 in display at /home/jeff/.julia/ImageView/src/display.jl:283
```

I can get past this error with the following change, which I assume is not really correct:

```
--- a/src/display.jl
+++ b/src/display.jl
@@ -235,7 +235,7 @@ function display{A<:AbstractArray}(img::A; proplist...)
     grid(framec, 1, 1, sticky="nsew")
     grid_rowconfigure(win, 1, weight=1) # scale this cell when the window resiz
     grid_columnconfigure(win, 1, weight=1)
-    c = Canvas(framec, ww, wh)
+    c = Canvas(win, ww, wh)
     imgc.c = c
     # Place the canvas and set its resize properties
     grid(c, 1, 1, sticky="nsew")        # fill the edges of its cell on all 4 s
```

I get the same error for other GUIs that ImageView opens.

Winston and other julia Tk code works for me on this system.

**Comment by philtomson** [comment]
I started getting this error recently as well (not sure how it started, at some point everything was working fine):

ERROR: getgc: Canvas is not drawable
 in wait_initialized at /home/phil/.julia/v0.3/Tk/src/tkwidget.jl:438
 in set_coords at /home/phil/.julia/v0.3/ImageView/src/display.jl:626
 in resize at /home/phil/.julia/v0.3/ImageView/src/display.jl:519
 in view at /home/phil/.julia/v0.3/ImageView/src/display.jl:319
 in view_featuremaps at /home/phil/work/WASP_TD/algorithm_dev/processing/depth_engine/src/learn_grad_whole.jl:28
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
while loading /home/phil/work/WASP_TD/algorithm_dev/processing/depth_engine/src/learn_grad_whole.jl, in expression starting on line 226

Julia 0.3.5 on Ubuntu 12.04

As suggested above, I checked out the gtk branch, but then I see:

ERROR: Gtk not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
while loading /home/phil/.julia/v0.3/ImageView/src/ImageView.jl, in expression starting on line 6

I've got libgtk2.0 and libgtk2.0-dev installed.

**Comment by timholy** [comment]
I've been seeing it too. I'm utterly swamped with other commitments right now, but you could do a `git  bisect` to figure out which change introduced the problem and then check out the version before the breakage.

**Comment by timholy** [comment]
(Let me know what you find, it will help me fix the problem when I get to it.)

**Comment by philtomson** [comment]
@timholy: you had added a tcl_doevent() into the TK/src/tkwidget.jl into the Canvas constructor (first line of the constructor it looks like from here: https://github.com/JuliaLang/Tk.jl/commit/f933493ec41450fbe694648055bca2cbe1e817dc

...but that addition is now gone. I haven't sifted through git to figure out when it went away, but there seem to have been some significant changes in tkwidget.jl since you added the tcl_doevent() call. I've added it back into my version of tkwidget.jl (at the beginning Canvas constructor) and that seems to be working fine. (had to do that since it appears the gtk branch of ImageView is broken at this point - I've filed another separate issue on that)

**Comment by timholy** [comment]
It was because some other shady character :smile: reverted that patch: https://github.com/JuliaLang/Tk.jl/commit/287b99fcf182f02f1d8ef97c346b9324a0a13bdb

It seems to fix problems for some people and break them for others.

This is part of why Gtk is better, but haven't had time to do the rewrite. I have quite a lot of goals for the rewrite, and that's an impediment to getting started.

**Comment by timholy** [comment]
Switched to Gtk, please open a new issue if still problematic.
